### ISSUE TITLE
fix: pipeline not working with hidden files in `opt_files`

### ISSUE THREAD

**Issue by tingtt** [tingtt/systemd-cd#9]
# Reproduce

```toml
[[systemd]]
opt_files = [".next/", "node_modules/", "package.json", "public/"]
```

# Task

- [x] Update hidden files beginning with "." at pipeline execution
